# Generated by Django 3.1.6 on 2021-04-02 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='sendEmailOnLogin',
            new_name='email_pref',
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='phone_number',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
